server:
  port: ${PORT:8080}

management:
  server:
    port: ${PORT:8080}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      path-mapping:
        health: /healthcheck
        info: /status
        ping: /ping
      base-path: /admin
      exposure:
        include:
          - health
          - info
          - ping

info:
  name: Ufl Bot Service
  version: @project.version@
  timezone: "Europe/London"
  build:
    version: @project.version@

token:

GOOGLE_CHROME_PATH: '/app/.apt/usr/bin/google_chrome'
CHROMEDRIVER_PATH: '/app/.chromedriver/bin/chromedriver'

logging:
  file:
    path: '/log'
    max-history: 2